/* 书店寻书 · 52本书籍数据（源自20张书店照片识别 + 网络资料整理；cover 为真实封面图路径，缺失时展示设计款封面） */
const BOOKS = [
  {
    title: "寒门子弟上大学",
    sub: "The Privileged Poor",
    author: "安东尼·亚伯拉罕·杰克",
    origin: "美",
    translator: "田雷 / 孙竞超",
    publisher: "生活·读书·新知三联书店",
    year: "2021",
    tag: "社科 · 教育",
    desc: "基于三年田野调查与上百位本科生访谈，揭示美国精英大学中寒门学子的真实处境——录取之后，大学何以仍在背弃贫困学生。",
    cover: "covers/hanmen.jpg",
    palette: { bg: "#dfe9f2", ink: "#1d3557", accent: "#e63946", coverA: "#aecbe8", coverB: "#f4f8fb", coverInk: "#274a78" }
  },
  {
    title: "性本恶",
    sub: "Inherent Vice",
    author: "托马斯·品钦",
    origin: "美",
    translator: "但汉松",
    publisher: "上海译文出版社",
    year: "2011",
    tag: "长篇小说",
    desc: "后现代文学大师品钦笔下的迷幻六十年代：洛杉矶私家侦探多克受前女友之托，卷入一场光怪陆离的失踪案。",
    cover: "covers/xingbene.jpg",
    palette: { bg: "#0f3d3e", ink: "#f2efe9", accent: "#e94f37", coverA: "#144d4a", coverB: "#e94f37", coverInk: "#f2efe9" }
  },
  {
    title: "我们这种叛徒",
    sub: "Our Kind of Traitor",
    author: "约翰·勒卡雷",
    origin: "英",
    translator: "杨懿晶",
    publisher: "上海译文出版社",
    year: "2015",
    tag: "间谍小说",
    desc: "一对英国情侣在加勒比度假时结识俄罗斯洗钱大亨，从此被卷入军情六处与俄国黑帮之间的漩涡。",
    cover: "covers/pantu.jpg",
    palette: { bg: "#14181f", ink: "#e8e6df", accent: "#c8a24b", coverA: "#1e2733", coverB: "#39465a", coverInk: "#e8e6df" }
  },
  {
    title: "城市絮语",
    sub: "Whispers of the City",
    author: "唐克扬",
    origin: "中",
    translator: "",
    publisher: "上海人民出版社",
    year: "2025",
    tag: "城市随笔",
    desc: "在街道、建筑与日常空间的细语中，重新打量我们栖居的城市——一部建筑学人的城市人文随笔。",
    cover: "covers/chengshi.jpg",
    palette: { bg: "#e9e4da", ink: "#2b2b2b", accent: "#6d5f4b", coverA: "#3a3632", coverB: "#d9d2c5", coverInk: "#f0ece4" }
  },
  {
    title: "香港道路探索",
    sub: "Hong Kong Road Study",
    author: "邱益彰 @道路研究社",
    origin: "港",
    translator: "",
    publisher: "非凡出版",
    year: "2021",
    tag: "设计 · 城市",
    desc: "香港第一本专述道路设计及字型的专书：路牌款式的演变、独有的交通标志，以及世界道路设计的考察笔记。",
    cover: "covers/xianggang.jpg",
    palette: { bg: "#f2f4f1", ink: "#1c4e2d", accent: "#2b6f43", coverA: "#2b6f43", coverB: "#f8faf7", coverInk: "#ffffff" }
  },
  {
    title: "三家分晋",
    sub: "",
    author: "丁一平",
    origin: "中",
    translator: "",
    publisher: "上海三联书店",
    year: "2025",
    tag: "战国史",
    desc: "从六卿主晋到三家分晋——纵横铺叙春秋战国之交的历史分水岭，剖析贵族政治向官僚政治的千年转型。",
    cover: "covers/sanjia.jpg",
    palette: { bg: "#12261e", ink: "#e5ddc8", accent: "#b08d3f", coverA: "#1c3a2d", coverB: "#0e1f18", coverInk: "#e5ddc8" }
  },
  {
    title: "苏轼十讲",
    sub: "",
    author: "朱刚",
    origin: "中",
    translator: "",
    publisher: "上海三联书店",
    year: "2019",
    tag: "人物 · 文学",
    desc: "以十个专题串联苏轼大起大落的传奇一生，将其置于历史与文化的洪流之中，融生平与诗文解读于一体。",
    cover: "covers/sushi.jpg",
    palette: { bg: "#eef0ea", ink: "#2f3b33", accent: "#7a936f", coverA: "#f5f6f2", coverB: "#cfd8c8", coverInk: "#39493d" }
  },
  {
    title: "与民国相遇",
    sub: "",
    author: "唐小兵",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2017",
    tag: "历史随笔",
    desc: "从民国史料生发的短篇随笔集：大变局中的碎屑与心情，乱世里的悲歌与传奇。",
    cover: "covers/minguo.jpg",
    palette: { bg: "#e7ddce", ink: "#3d2f24", accent: "#8c5b33", coverA: "#d9c9b0", coverB: "#f2ead9", coverInk: "#4a3826" }
  },
  {
    title: "中国转向内在",
    sub: "China Turning Inward",
    author: "刘子健",
    origin: "美",
    translator: "赵冬梅",
    publisher: "江苏人民出版社",
    year: "2012",
    tag: "宋史",
    desc: "两宋之际政治与文化的深刻转型：专制皇权膨胀、士人转向道德内省，中国文化自此\u201c转向内在\u201d。",
    cover: "covers/neizai.jpg",
    palette: { bg: "#1b2740", ink: "#dfe3ec", accent: "#8fa8d8", coverA: "#243c63", coverB: "#31446b", coverInk: "#dfe3ec" }
  },
  {
    title: "今天我不愿面对自己",
    sub: "Heute wär ich mir lieber nicht begegnet",
    author: "赫塔·米勒",
    origin: "德",
    translator: "沈锡良",
    publisher: "后浪 × 贵州人民出版社",
    year: "2021",
    tag: "诺奖小说",
    desc: "\u201c罗马尼亚三部曲\u201d第三部：被传唤受审的制衣厂女工在电车上回忆一生，写尽极权之下个体的恐惧与尊严。",
    cover: "covers/jintian.jpg",
    palette: { bg: "#25211f", ink: "#efe7dc", accent: "#c94f38", coverA: "#332c28", coverB: "#c94f38", coverInk: "#efe7dc" }
  },
  {
    title: "克里斯托弗和他的同类",
    sub: "Christopher and His Kind",
    author: "克里斯托弗·伊舍伍德",
    origin: "英",
    translator: "陶凌寅",
    publisher: "上海译文出版社",
    year: "2020",
    tag: "自传体小说",
    desc: "从1929年的柏林到1939年旅居美国，伊舍伍德坦诚回望战前欧洲十年岁月与自我身份。",
    cover: "covers/christopher.jpg",
    palette: { bg: "#d9cfc4", ink: "#33261f", accent: "#7d4a2a", coverA: "#4a352a", coverB: "#c7b9a5", coverInk: "#efe6d8" }
  },
  {
    title: "正义联盟",
    sub: "Justice League · 12 Stories",
    author: "马克·米勒 等",
    origin: "英",
    translator: "孙鹏 / 陈潇",
    publisher: "民主与建设出版社 · 后浪漫",
    year: "2017",
    tag: "DC 漫画",
    desc: "世界上最伟大英雄的12个故事：从\u201c神秘斯塔罗\u201d现身到对抗达克赛德，正义联盟的黄金岁月合集。",
    cover: "covers/justice.jpg",
    palette: { bg: "#101018", ink: "#f0f2f5", accent: "#2c6fd1", coverA: "#15151f", coverB: "#2c6fd1", coverInk: "#f0f2f5" }
  },
  {
    title: "江村经济",
    sub: "Peasant Life in China",
    author: "费孝通",
    origin: "中",
    translator: "",
    publisher: "北京大学出版社 等",
    year: "1939",
    tag: "社会学经典",
    desc: "基于对江苏开弦弓村的实地考察写成的博士论文，被马林诺夫斯基誉为人类学发展史上的里程碑。",
    cover: "covers/jiangcun.jpg",
    palette: { bg: "#2d3a4a", ink: "#e8e4d8", accent: "#c8b273", coverA: "#39485c", coverB: "#22303e", coverInk: "#e8e4d8" }
  },
  {
    title: "夏志清夏济安书信集",
    sub: "",
    author: "夏志清 / 夏济安",
    origin: "中",
    translator: "王洞 主编 · 季进 编注",
    publisher: "浙江人民出版社 · 后浪",
    year: "2017",
    tag: "书信集",
    desc: "现代文学批评界两大巨擘的六百余封私密书信，十七年间谈文论艺、殷勤存问的吉光片羽。",
    cover: "covers/xiazhiqing.jpg",
    palette: { bg: "#ece6db", ink: "#31404f", accent: "#5b7a99", coverA: "#f4f0e8", coverB: "#c6cfd8", coverInk: "#31404f" }
  },
  {
    title: "漫谈中国文化",
    sub: "金融 · 企业 · 国学",
    author: "南怀瑾 讲述",
    origin: "中",
    translator: "",
    publisher: "东方出版社",
    year: "2008",
    tag: "国学讲录",
    desc: "太湖大学堂三次讲座辑录：从《管子》《货殖列传》谈起，纵论传统文化中的金融、企业与经济之道。",
    cover: "covers/mantan.jpg",
    palette: { bg: "#f0e7d8", ink: "#54331d", accent: "#b8860b", coverA: "#e9d9ba", coverB: "#f7f0e2", coverInk: "#54331d" }
  },
  {
    title: "未厌居习作",
    sub: "",
    author: "叶绍钧（叶圣陶）",
    origin: "中",
    translator: "",
    publisher: "中国青年出版社",
    year: "1935 / 2012",
    tag: "现代散文",
    desc: "\u201c未厌居\u201d为叶圣陶书斋之名。文字淳厚平实，一位现代文学与教育大家对日常生活的静观。",
    cover: "covers/weiyanju.jpg",
    palette: { bg: "#e4e7e3", ink: "#3c4a41", accent: "#748c7d", coverA: "#f2f4f1", coverB: "#cdd6cf", coverInk: "#3c4a41" }
  },
  {
    title: "金陵汉诗",
    sub: "",
    author: "邓攀 编著",
    origin: "中",
    translator: "",
    publisher: "南京出版社",
    year: "2019",
    tag: "诗歌 · 地方文史",
    desc: "辑录与金陵相关的汉诗作品，在字句平仄间打捞一座古都绵延千年的诗意文脉。",
    palette: { bg: "#cfe8e6", ink: "#1f4e4a", accent: "#2e7d76", coverA: "#5cb8ae", coverB: "#e8f5f3", coverInk: "#134744" }
  },
  {
    title: "金刚经讲义",
    sub: "",
    author: "江味农",
    origin: "中",
    translator: "",
    publisher: "华东师范大学出版社 等",
    year: "1940年代成书",
    tag: "佛学",
    desc: "民国居士江味农倾注毕生心血的遗著，被誉为解释《金刚经》的最佳读本之一。",
    cover: "covers/jingang.jpg",
    palette: { bg: "#efe3cf", ink: "#5a4326", accent: "#a67c3d", coverA: "#d9c193", coverB: "#f5ecda", coverInk: "#5a4326" }
  },
  {
    title: "蛮族世界的拼图",
    sub: "The Barbarians",
    author: "彼得·柏伽基",
    origin: "波",
    translator: "",
    publisher: "中国社会科学出版社 · 鼓楼新悦",
    year: "2021",
    tag: "考古 · 欧洲史",
    desc: "在希腊罗马的文字记载之外，用考古证据重建欧洲史前居民数千年的真实生活图景。",
    cover: "covers/manzu.jpg",
    palette: { bg: "#4a4a42", ink: "#e9e5d8", accent: "#c2a25a", coverA: "#5c5a4c", coverB: "#3a3a34", coverInk: "#e9e5d8" }
  },
  {
    title: "霍布斯与共和主义自由",
    sub: "Hobbes and Republican Liberty",
    author: "昆廷·斯金纳",
    origin: "英",
    translator: "",
    publisher: "上海三联书店",
    year: "2011",
    tag: "政治哲学",
    desc: "剑桥思想史学派代表作：围绕霍布斯与古典共和主义关于\u201c自由\u201d的论争，重构现代政治思想的关键脉络。",
    cover: "covers/hobbes.jpg",
    palette: { bg: "#f4f1ea", ink: "#23211e", accent: "#8c8577", coverA: "#faf8f3", coverB: "#dcd6c9", coverInk: "#23211e" }
  },
  {
    title: "中国古建筑二十讲",
    sub: "",
    author: "楼庆西",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2001",
    tag: "建筑文化",
    desc: "清华建筑学者的经典讲义：以二十讲通俗系统地讲述中国古建筑的类型、结构与文化内涵。",
    cover: "covers/gujianzhu.jpg",
    palette: { bg: "#3d2b26", ink: "#eadfd0", accent: "#c8552c", coverA: "#5a3a30", coverB: "#2e211d", coverInk: "#eadfd0" }
  },
  {
    title: "中国古代纪时考",
    sub: "",
    author: "张衍田",
    origin: "中",
    translator: "",
    publisher: "上海古籍出版社",
    year: "2019",
    tag: "文史考据",
    desc: "对中国古代纪年、纪月、纪日、纪时制度的系统考证，文史研究者的案头工具书。",
    cover: "covers/jishikao.jpg",
    palette: { bg: "#4b2530", ink: "#ecdfd2", accent: "#caa14e", coverA: "#5f3040", coverB: "#3a1c26", coverInk: "#ecdfd2" }
  },
  {
    title: "人类简史",
    sub: "Sapiens: A Brief History of Humankind",
    author: "尤瓦尔·赫拉利",
    origin: "以",
    translator: "林俊宏",
    publisher: "中信出版社",
    year: "2014",
    tag: "历史 · 社科",
    desc: "从认知革命、农业革命到科学革命，赫拉利以宏大视角重述十万年人类史，追问智人何以主宰地球、又将走向何方。",
    cover: "covers/renlei.jpg",
    palette: { bg: "#e8e6e1", ink: "#2b2b2b", accent: "#c89b5a", coverA: "#d9d5cd", coverB: "#f2f0ec", coverInk: "#2b2b2b" }
  },
  {
    title: "古希腊社会生活史",
    sub: "那些不在历史书里的事儿",
    author: "达玛丽斯·罗梅罗·冈萨雷斯",
    origin: "西",
    translator: "宋若筠",
    publisher: "金城出版社",
    year: "2026",
    tag: "古典 · 生活史",
    desc: "告别冰冷的宏大叙事，走进古希腊人的烟火日常：从私人生活到大众文化，看见一个鲜活、怪诞而迷人的古希腊社会。",
    cover: "covers/guxila.jpg",
    palette: { bg: "#17181c", ink: "#ece7db", accent: "#c9a227", coverA: "#23252c", coverB: "#101114", coverInk: "#ece7db" }
  },
  {
    title: "我的生活很重要",
    sub: "过自己想要的生活",
    author: "彭瑞心",
    origin: "中",
    translator: "",
    publisher: "中信出版集团",
    year: "2026",
    tag: "生活 · 随笔",
    desc: "家庭美学实践者“啾啾妈”首部作品：从忙乱到从容，把日子变轻松的36个解法。",
    cover: "covers/wodeshenghuo.jpg",
    palette: { bg: "#8e3b3b", ink: "#f7ece4", accent: "#e0b089", coverA: "#96403f", coverB: "#7a3232", coverInk: "#f7ece4" }
  },
  {
    title: "当战争来敲门",
    sub: "二战中的经济、人性和平民",
    author: "理查德·奥弗里 主编",
    origin: "英",
    translator: "刘晓同 / 刘志良",
    publisher: "江苏凤凰文艺出版社",
    year: "2025",
    tag: "二战史",
    desc: "牛津大学出版社原版引进：从经济崩溃到全面战争，谁是推手？谁上战场？谁在幕后？谁得利益？",
    cover: "covers/dangzhanzheng.jpg",
    palette: { bg: "#1c2a4a", ink: "#e9ecf2", accent: "#d64545", coverA: "#24365e", coverB: "#16223c", coverInk: "#e9ecf2" }
  },
  {
    title: "治世与烟火",
    sub: "中国古代官僚制度与社会生活史",
    author: "郭建",
    origin: "中",
    translator: "",
    publisher: "团结出版社",
    year: "2025",
    tag: "制度史",
    desc: "复旦大学教授以史学巨眼透视制度肌理，看两千年来“治世”理想与“烟火”现实的碰撞。",
    cover: "covers/zhishi.jpg",
    palette: { bg: "#efe6d6", ink: "#4a3421", accent: "#b8442c", coverA: "#f4ecdd", coverB: "#ddcdb2", coverInk: "#4a3421" }
  },
  {
    title: "古人的日常生活（全五册）",
    sub: "服饰 · 膳食 · 茶饮 · 把玩 · 家居",
    author: "陈元綵 等",
    origin: "中",
    translator: "",
    publisher: "北京理工大学出版社",
    year: "2022",
    tag: "传统文化",
    desc: "一套古人日常生活百科：从衣冠服饰到茶饮膳食、家居陈设与赏玩之物，图文重建古代中国人的衣食住行。",
    cover: "covers/gurenrichang.jpg",
    palette: { bg: "#ece2cf", ink: "#5a4632", accent: "#c0392b", coverA: "#f2e9d8", coverB: "#d9c9ac", coverInk: "#5a4632" }
  },
  {
    title: "全球化突围",
    sub: "模式、架构与风险防控",
    author: "鲍乐东",
    origin: "中",
    translator: "",
    publisher: "浙江大学出版社",
    year: "2026",
    tag: "商业 · 管理",
    desc: "模式选择×架构设计×风险防控，企业出海全链路实战体系，直击中国企业全球化的隐形陷阱。",
    cover: "covers/quanqiuhua.jpg",
    palette: { bg: "#1d4f9e", ink: "#f0f4fa", accent: "#7fb2f0", coverA: "#2458aa", coverB: "#163e80", coverInk: "#f0f4fa" }
  },
  {
    title: "即兴表达",
    sub: "轻松留下好印象的沟通技巧",
    author: "王达峰",
    origin: "中",
    translator: "",
    publisher: "浙江大学出版社",
    year: "2020",
    tag: "沟通 · 成长",
    desc: "15秒抓住注意力，3句话说清楚重点——从逻辑到共情，用模型与结构掌控每一个沟通的关键时刻。",
    cover: "covers/jixing.jpg",
    palette: { bg: "#f3d9c9", ink: "#3f3a36", accent: "#8aa87c", coverA: "#f7e3d6", coverB: "#e8c8b4", coverInk: "#3f3a36" }
  },
  {
    title: "27小时事件经济",
    sub: "",
    author: "张毅成",
    origin: "中",
    translator: "",
    publisher: "东方出版社",
    year: "2025",
    tag: "营销 · 传播",
    desc: "不到27小时，只是热闹；超过27小时，才是经济——解码事件营销的传播周期与商业转化。",
    cover: "covers/ershiqi.jpg",
    palette: { bg: "#21294a", ink: "#f0eeea", accent: "#d8322e", coverA: "#d8322e", coverB: "#21294a", coverInk: "#ffffff" }
  },
  {
    title: "商人与中国社会",
    sub: "一部共生演进史",
    author: "陈润 / 邓玉蕊",
    origin: "中",
    translator: "",
    publisher: "浙江大学出版社",
    year: "2026",
    tag: "商业史",
    desc: "商人以实业推动社会进步，社会以制度为商人划定发展方向——书写中国商业与社会的千年演进篇章。",
    cover: "covers/shangren.jpg",
    palette: { bg: "#101d33", ink: "#e8e2d2", accent: "#caa969", coverA: "#16263f", coverB: "#0b1523", coverInk: "#e8e2d2" }
  },
  {
    title: "财报决策力",
    sub: "从关键数据分析到高效决策",
    author: "徐晶",
    origin: "中",
    translator: "",
    publisher: "中国友谊出版公司",
    year: "2026",
    tag: "财务 · 管理",
    desc: "企业主、管理层、债权人、投资人的实战手册：穿透关键数据背后的盈利能力、营运能力与投资价值。",
    cover: "covers/juece.jpg",
    palette: { bg: "#b02722", ink: "#fdf3ea", accent: "#d9a45c", coverA: "#ba2d26", coverB: "#8f1e1a", coverInk: "#fdf3ea" }
  },
  {
    title: "帝国棋局",
    sub: "张居正的晚明改革与博弈",
    author: "齐悦",
    origin: "中",
    translator: "",
    publisher: "中国友谊出版公司",
    year: "2026",
    tag: "明史",
    desc: "孤臣铁腕，挽倾颓之国——十年改革，续大明天命。在权谋与困局交织处，重看张居正的人生史诗。",
    cover: "covers/diguoqiju.jpg",
    palette: { bg: "#f4e3c8", ink: "#7a3a1c", accent: "#b4552a", coverA: "#f8ecd6", coverB: "#e6c9a0", coverInk: "#7a3a1c" }
  },
  {
    title: "精神帝国",
    sub: "Empires of the Mind",
    author: "罗伯特·吉尔德",
    origin: "英",
    translator: "孙伟",
    publisher: "浙江大学出版社",
    year: "2026",
    tag: "帝国史",
    desc: "殖民历史与当代政治：追溯冷战结束以来帝国主义思维的复苏，剖析英法帝国遗产如何塑造当下。",
    cover: "covers/jingshendiguo.jpg",
    palette: { bg: "#e9e4d4", ink: "#24211c", accent: "#d8b93c", coverA: "#efece1", coverB: "#d8cdb2", coverInk: "#24211c" }
  },
  {
    title: "太平前夜",
    sub: "五代十国的乱世诗心",
    author: "陈尚君",
    origin: "中",
    translator: "",
    publisher: "上海人民出版社",
    year: "2026",
    tag: "文学史",
    desc: "唐诗学大家陈尚君新作：在五代十国的兵戈乱世里，打捞诗人们未曾燄灭的诗心与斯文。",
    cover: "covers/taiping.jpg",
    palette: { bg: "#2b2d7e", ink: "#ece4d2", accent: "#d9a441", coverA: "#34378f", coverB: "#1f2160", coverInk: "#ece4d2" }
  },
  {
    title: "红顶商人胡雪岩",
    sub: "",
    author: "高阳",
    origin: "台",
    translator: "",
    publisher: "江苏文艺出版社 · 读客",
    year: "2012",
    tag: "历史小说",
    desc: "讲透中国传统商道人情的至高经典：从店伙计到大清首富只用了30年，从首富到抄家破产只用了3天。",
    cover: "covers/hongding.jpg",
    palette: { bg: "#1a1714", ink: "#efe6d8", accent: "#cf2f24", coverA: "#262019", coverB: "#0f0d0b", coverInk: "#efe6d8" }
  },
  {
    title: "未央歌",
    sub: "",
    author: "鹿桥",
    origin: "中",
    translator: "",
    publisher: "黄山书社",
    year: "2007",
    tag: "长篇小说",
    desc: "以西南联大为背景的青春长歌：战火中的昆明校园，一群大学生的友情、爱情与理想主义岁月。",
    cover: "covers/weiyangge.jpg",
    palette: { bg: "#33504e", ink: "#dfe6e2", accent: "#86a89f", coverA: "#3c5c58", coverB: "#253c3a", coverInk: "#dfe6e2" }
  },
  {
    title: "大唐李白·凤凰台",
    sub: "",
    author: "张大春",
    origin: "台",
    translator: "",
    publisher: "广西师范大学出版社 · 理想国",
    year: "2014",
    tag: "历史小说",
    desc: "融历史、传记、小说、诗论于一体：重建灿烂迷离的盛唐景观，再现李白声名背后的斑斓世相。",
    cover: "covers/datangli.jpg",
    palette: { bg: "#f2ece2", ink: "#322c28", accent: "#b7383e", coverA: "#b7383e", coverB: "#f6f1e7", coverInk: "#ffffff" }
  },
  {
    title: "大唐李白·将进酒",
    sub: "",
    author: "张大春",
    origin: "台",
    translator: "",
    publisher: "广西师范大学出版社 · 理想国",
    year: "2015",
    tag: "历史小说",
    desc: "“大唐李白”第三卷：古来圣贤皆寂寞，惟有饮者留其名——李白浪游长安前夜的诗与远方。",
    cover: "covers/jiangjinjiu.jpg",
    palette: { bg: "#ececea", ink: "#33302c", accent: "#8f8a82", coverA: "#f4f3f0", coverB: "#d8d6d1", coverInk: "#33302c" }
  },
  {
    title: "北归记·接引葫芦",
    sub: "《野葫芦引》第四卷 · 末卷",
    author: "宗璞",
    origin: "中",
    translator: "",
    publisher: "人民文学出版社",
    year: "2019",
    tag: "长篇小说",
    desc: "“野葫芦引”四部曲收官之作：西南联大师生北归之后的命运流转，一代知识分子的心灵史诗。",
    cover: "covers/beiguiji.jpg",
    palette: { bg: "#f0f2f4", ink: "#3a4a6b", accent: "#5b74a8", coverA: "#f7f8fa", coverB: "#dfe4ec", coverInk: "#3a4a6b" }
  },
  {
    title: "我们并不知道",
    sub: "",
    author: "金宇澄",
    origin: "中",
    translator: "",
    publisher: "东美出版（台北）",
    year: "2017",
    tag: "随笔 · 谈话",
    desc: "《繁花》作者金宇澄的随笔谈话集：关于记忆、城市与写作，那些“我们并不知道”的人间细节。",
    cover: "covers/bingbuzhidao.jpg",
    palette: { bg: "#cbb287", ink: "#3c2f1c", accent: "#8c6b3a", coverA: "#d8c49b", coverB: "#b89a68", coverInk: "#3c2f1c" }
  },
  {
    title: "千江有水千江月",
    sub: "",
    author: "萧丽红",
    origin: "台",
    translator: "",
    publisher: "人民文学出版社",
    year: "2006",
    tag: "长篇小说",
    desc: "台湾文学经典：布袋镇的大家族里，贞观与大信含蓄悠长的爱情，写尽旧式人情之美。",
    cover: "covers/qianjiang.jpg",
    palette: { bg: "#f2f4f6", ink: "#2c4a72", accent: "#4a72a8", coverA: "#f8fafc", coverB: "#dbe6f0", coverInk: "#2c4a72" }
  },
  {
    title: "书店四季",
    sub: "Confessions of a Bookseller",
    author: "肖恩·白塞尔",
    origin: "英",
    translator: "顾真",
    publisher: "北京日报出版社",
    year: "2021",
    tag: "书店 · 随笔",
    desc: "《书店日记》续篇：苏格兰最大二手书店又一年——毒舌店主与顾客、店猫和旧书相伴的四季流水账。",
    cover: "covers/shudianriji.jpg",
    palette: { bg: "#1f6f5c", ink: "#f4efdd", accent: "#e0475c", coverA: "#268069", coverB: "#164f42", coverInk: "#f4efdd" }
  },
  {
    title: "诗里的大唐",
    sub: "由诗人的命运与诗作交织成的大唐史",
    author: "最爱君",
    origin: "中",
    translator: "",
    publisher: "时报文化",
    year: "2022",
    tag: "诗歌 · 唐史",
    desc: "诗以言史，史以入诗：在李白杜甫们的悲欢浮沉里，读懂大唐三百年的兴衰流转。",
    palette: { bg: "#efe1c6", ink: "#6b3a20", accent: "#c2452c", coverA: "#e8d3a8", coverB: "#f6ecd8", coverInk: "#6b3a20" }
  },
  {
    title: "难以驯化的利维坦",
    sub: "基于韦伯“国家社会学”的研究",
    author: "陈涛",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2026",
    tag: "政治社会学",
    desc: "三联·哈佛燕京学术丛书：以韦伯“国家社会学”为鑰，剖析现代国家这头难以驯化的利维坦。",
    cover: "covers/liweitan.jpg",
    palette: { bg: "#dfe5df", ink: "#2c433a", accent: "#52705f", coverA: "#b9c8bd", coverB: "#33544a", coverInk: "#eef2ee" }
  },
  {
    title: "万历十五年",
    sub: "1587, a Year of No Significance",
    author: "黄仁宇",
    origin: "美",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "1997",
    tag: "明史经典",
    desc: "大历史观开山之作：万历十五年，表面四海升平，实则大明王朝的症结已在无声处一一显露。",
    cover: "covers/wanli.jpg",
    palette: { bg: "#efe9db", ink: "#4a3d2a", accent: "#a08050", coverA: "#f4efe2", coverB: "#d9cdb2", coverInk: "#4a3d2a" }
  },
  {
    title: "伽达默尔与东方思想",
    sub: "与伽达默尔同行",
    author: "张能为",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2026",
    tag: "哲学",
    desc: "“与伽达默尔同行”书系：考察诠释学大师与东方思想的对话可能，探寻中西哲学互鉴的路径。",
    cover: "covers/gadamoer.jpg",
    palette: { bg: "#16457e", ink: "#eef2f7", accent: "#d4763a", coverA: "#1c528f", coverB: "#0f3560", coverInk: "#eef2f7" }
  },
  {
    title: "新定位时代",
    sub: "定位决定地位，眼界决定境界",
    author: "邓德隆",
    origin: "中",
    translator: "",
    publisher: "上海三联书店",
    year: "2022",
    tag: "商业 · 战略",
    desc: "特劳特全球总裁邓德隆二十年定位实践：郎酒、方太、加多宝等分行业案例的战略心法。",
    cover: "covers/xindingwei.jpg",
    palette: { bg: "#14523c", ink: "#f0ead8", accent: "#d43a2a", coverA: "#185f46", coverB: "#0d3d2c", coverInk: "#f0ead8" }
  },
  {
    title: "星汉灿烂，幸甚至哉",
    sub: "",
    author: "关心则乱",
    origin: "中",
    translator: "",
    publisher: "江苏凤凰文艺出版社",
    year: "2022",
    tag: "古代言情",
    desc: "一个女孩子的成长：程少商与凌不疑的东汉风云，热播剧《星汉灿烂》原著小说。",
    cover: "covers/jianan.jpg",
    palette: { bg: "#1c2b4a", ink: "#f2e6d8", accent: "#e08a4a", coverA: "#253a63", coverB: "#131f38", coverInk: "#f2e6d8" }
  },
  {
    title: "正义的褶皱",
    sub: "热点案件的法理重构",
    author: "桑本谦",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2026",
    tag: "法学",
    desc: "深度拆解十大热点案例：不止还原案件来龙去脉，更聚焦法律的底层逻辑，培养法律直觉。",
    cover: "covers/zhengyi.jpg",
    palette: { bg: "#232c40", ink: "#edeef2", accent: "#b03030", coverA: "#2c3852", coverB: "#171d2c", coverInk: "#edeef2" }
  },
  {
    title: "记忆",
    sub: "Anamnesis · 历史与政治理论",
    author: "埃里克·沃格林",
    origin: "美",
    translator: "朱成明",
    publisher: "华东师范大学出版社",
    year: "2017",
    tag: "政治哲学",
    desc: "沃格林思想成熟期的核心文本：以“记忆”为轴，追索历史与政治理论中意识哲学的根基。",
    cover: "covers/huiyi.jpg",
    palette: { bg: "#e6ddd0", ink: "#40332a", accent: "#8c4a32", coverA: "#efe8dc", coverB: "#d4c7b4", coverInk: "#40332a" }
  }
];
