/* 书店寻书 · 52本书籍数据（源自20张书店照片识别 + 网络资料整理；cover 为真实封面图路径，缺失时展示设计款封面） */
const BOOKS = [
  {
    title: "寒门子弟上大学",
    sub: "The Privileged Poor",
    author: "安东尼·亚伯拉罕·杰克",
    origin: "美",
    translator: "田雷 / 孙竞超",
    publisher: "生活·读书·新知三联书店",
    year: "2021",
    tag: "社科 · 教育",
    cat: "社科历史",
    desc: "基于三年田野调查与上百位本科生访谈，揭示美国精英大学中寒门学子的真实处境——录取之后，大学何以仍在背弃贫困学生。作者区分“有备而来的穷学生”与“双重贫困生”，指出仅有入场券远远不够：从社交礼仪到隐性规则，校园处处是看不见的门槛。",
    cover: "covers/hanmen.jpg",
    palette: { bg: "#dfe9f2", ink: "#1d3557", accent: "#e63946", coverA: "#aecbe8", coverB: "#f4f8fb", coverInk: "#274a78" }
  },
  {
    title: "性本恶",
    sub: "Inherent Vice",
    author: "托马斯·品钦",
    origin: "美",
    translator: "但汉松",
    publisher: "上海译文出版社",
    year: "2011",
    tag: "长篇小说",
    cat: "文学小说",
    desc: "后现代文学大师品钦笔下的迷幻六十年代：洛杉矶私家侦探多克受前女友之托，卷入一场光怪陆离的失踪案。冲浪客、瘾君子、地产大亨与神秘组织“金獗牙”轮番登场，在侦探小说的外壳下，写尽嘻皮时代落幕时分的迷惘与哀愁。",
    cover: "covers/xingbene.jpg",
    palette: { bg: "#0f3d3e", ink: "#f2efe9", accent: "#e94f37", coverA: "#144d4a", coverB: "#e94f37", coverInk: "#f2efe9" }
  },
  {
    title: "我们这种叛徒",
    sub: "Our Kind of Traitor",
    author: "约翰·勒卡雷",
    origin: "英",
    translator: "杨懿晶",
    publisher: "上海译文出版社",
    year: "2015",
    tag: "间谍小说",
    cat: "文学小说",
    desc: "一对英国情侣在加勒比度假时结识俄罗斯洗钱大亨，从此被卷入军情六处与俄国黑帮之间的漩涡。冷战落幕后的间谍世界更加暖昧凶险，勒卡雷以老辣笔法写透金钱、忠诚与背叛——所谓叛徒，往往只是想活下去的普通人。",
    cover: "covers/pantu.jpg",
    palette: { bg: "#14181f", ink: "#e8e6df", accent: "#c8a24b", coverA: "#1e2733", coverB: "#39465a", coverInk: "#e8e6df" }
  },
  {
    title: "城市絮语",
    sub: "Whispers of the City",
    author: "唐克扬",
    origin: "中",
    translator: "",
    publisher: "上海人民出版社",
    year: "2025",
    tag: "城市随笔",
    cat: "随笔书信",
    desc: "在街道、建筑与日常空间的细语中，重新打量我们栖居的城市——一部建筑学人的城市人文随笔。从城门旧影到玻璃幕墙，从菜市烟火到地铁人流，作者以建筑史的眼光与文学的笔触，唤回被匆忙脚步略过的城市记忆与空间诗意。",
    cover: "covers/chengshi.jpg",
    palette: { bg: "#e9e4da", ink: "#2b2b2b", accent: "#6d5f4b", coverA: "#3a3632", coverB: "#d9d2c5", coverInk: "#f0ece4" }
  },
  {
    title: "香港道路探索",
    sub: "Hong Kong Road Study",
    author: "邱益彰 @道路研究社",
    origin: "港",
    translator: "",
    publisher: "非凡出版",
    year: "2021",
    tag: "设计 · 城市",
    cat: "艺术设计",
    desc: "香港第一本专述道路设计及字型的专书：路牌款式的演变、独有的交通标志，以及世界道路设计的考察笔记。从监狱体字型到回旋处与行人过路灯，道路研究社把街头习以为常的细节，读成一部活的城市设计史。",
    cover: "covers/xianggang.jpg",
    palette: { bg: "#f2f4f1", ink: "#1c4e2d", accent: "#2b6f43", coverA: "#2b6f43", coverB: "#f8faf7", coverInk: "#ffffff" }
  },
  {
    title: "三家分晋",
    sub: "",
    author: "丁一平",
    origin: "中",
    translator: "",
    publisher: "上海三联书店",
    year: "2025",
    tag: "战国史",
    cat: "社科历史",
    desc: "从六卿主晋到三家分晋——纵横铺叙春秋战国之交的历史分水岭，剖析贵族政治向官僚政治的千年转型。韩赵魏如何蚕食公室、智氏何以一夕覆亡，作者以扎实史料与晓畅叙事，重现礼崩乐坏时代的权谋与变局。",
    cover: "covers/sanjia.jpg",
    palette: { bg: "#12261e", ink: "#e5ddc8", accent: "#b08d3f", coverA: "#1c3a2d", coverB: "#0e1f18", coverInk: "#e5ddc8" }
  },
  {
    title: "苏轼十讲",
    sub: "",
    author: "朱刚",
    origin: "中",
    translator: "",
    publisher: "上海三联书店",
    year: "2019",
    tag: "人物 · 文学",
    cat: "社科历史",
    desc: "以十个专题串联苏轼大起大落的传奇一生，将其置于历史与文化的洪流之中，融生平与诗文解读于一体。从乌台诗案到黄州突围，从庐山访禅到儋州讲学，复旦中文系名课讲义，读罢方知何谓“人间不可无一难能有二”。",
    cover: "covers/sushi.jpg",
    palette: { bg: "#eef0ea", ink: "#2f3b33", accent: "#7a936f", coverA: "#f5f6f2", coverB: "#cfd8c8", coverInk: "#39493d" }
  },
  {
    title: "与民国相遇",
    sub: "",
    author: "唐小兵",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2017",
    tag: "历史随笔",
    cat: "社科历史",
    desc: "从民国史料生发的短篇随笔集：大变局中的碎屑与心情，乱世里的悲歌与传奇。知识人的进退出处、报刊上的论战风波、日记书信里的私人心事，作者以史家的敏感打捞时代边角料，拼出一幅有体温的民国肖像。",
    cover: "covers/minguo.jpg",
    palette: { bg: "#e7ddce", ink: "#3d2f24", accent: "#8c5b33", coverA: "#d9c9b0", coverB: "#f2ead9", coverInk: "#4a3826" }
  },
  {
    title: "中国转向内在",
    sub: "China Turning Inward",
    author: "刘子健",
    origin: "美",
    translator: "赵冬梅",
    publisher: "江苏人民出版社",
    year: "2012",
    tag: "宋史",
    cat: "社科历史",
    desc: "两宋之际政治与文化的深刻转型：专制皇权膨胀、士人转向道德内省，中国文化自此\u201c转向内在\u201d。海外宋史名家刘子健的经典之作，以精炼笔墨回答了一个大问题——曾经开放外向的唐宋文明，为何在南宋以后渐趋内敛保守。",
    cover: "covers/neizai.jpg",
    palette: { bg: "#1b2740", ink: "#dfe3ec", accent: "#8fa8d8", coverA: "#243c63", coverB: "#31446b", coverInk: "#dfe3ec" }
  },
  {
    title: "今天我不愿面对自己",
    sub: "Heute wär ich mir lieber nicht begegnet",
    author: "赫塔·米勒",
    origin: "德",
    translator: "沈锡良",
    publisher: "后浪 × 贵州人民出版社",
    year: "2021",
    tag: "诺奖小说",
    cat: "文学小说",
    desc: "\u201c罗马尼亚三部曲\u201d第三部：被传唤受审的制衣厂女工在电车上回忆一生，写尽极权之下个体的恐惧与尊严。诺贝尔文学奖得主赫塔·米勒以碎片般的意象与冷峻诗性的语言，让一次通往审讯室的旅程，成为对整个时代的控诉。",
    cover: "covers/jintian.jpg",
    palette: { bg: "#25211f", ink: "#efe7dc", accent: "#c94f38", coverA: "#332c28", coverB: "#c94f38", coverInk: "#efe7dc" }
  },
  {
    title: "克里斯托弗和他的同类",
    sub: "Christopher and His Kind",
    author: "克里斯托弗·伊舍伍德",
    origin: "英",
    translator: "陶凌寅",
    publisher: "上海译文出版社",
    year: "2020",
    tag: "自传体小说",
    cat: "文学小说",
    desc: "从1929年的柏林到1939年旅居美国，伊舍伍德坦诚回望战前欧洲十年岁月与自我身份。魏玛柏林的夜店与街垒、辗转欧洲的流亡与爱恋，这部自传体小说以罕见的诚实直面欲望与写作，也是《柏林故事集》背后的真实版本。",
    cover: "covers/christopher.jpg",
    palette: { bg: "#d9cfc4", ink: "#33261f", accent: "#7d4a2a", coverA: "#4a352a", coverB: "#c7b9a5", coverInk: "#efe6d8" }
  },
  {
    title: "正义联盟",
    sub: "Justice League · 12 Stories",
    author: "马克·米勒 等",
    origin: "英",
    translator: "孙鹏 / 陈潇",
    publisher: "民主与建设出版社 · 后浪漫",
    year: "2017",
    tag: "DC 漫画",
    cat: "漫画",
    desc: "世界上最伟大英雄的12个故事：从\u201c神秘斯塔罗\u201d现身到对抗达克赛德，正义联盟的黄金岁月合集。超人、蝙蝠侠、神奇女侠、闪电侠齐聚一堂，横跨半个世纪的经典刊目精选，见证美漫宇宙最耀眼组合的诞生与传奇。",
    cover: "covers/justice.jpg",
    palette: { bg: "#101018", ink: "#f0f2f5", accent: "#2c6fd1", coverA: "#15151f", coverB: "#2c6fd1", coverInk: "#f0f2f5" }
  },
  {
    title: "江村经济",
    sub: "Peasant Life in China",
    author: "费孝通",
    origin: "中",
    translator: "",
    publisher: "北京大学出版社 等",
    year: "1939",
    tag: "社会学经典",
    cat: "社科历史",
    desc: "基于对江苏开弦弓村的实地考察写成的博士论文，被马林诺夫斯基誉为人类学发展史上的里程碑。土地制度、蚕丝产业、家庭结构与消费习惯——费孝通以一个村庄为切片，让世界第一次看清中国农民真实的经济生活。",
    cover: "covers/jiangcun.jpg",
    palette: { bg: "#2d3a4a", ink: "#e8e4d8", accent: "#c8b273", coverA: "#39485c", coverB: "#22303e", coverInk: "#e8e4d8" }
  },
  {
    title: "夏志清夏济安书信集",
    sub: "",
    author: "夏志清 / 夏济安",
    origin: "中",
    translator: "王洞 主编 · 季进 编注",
    publisher: "浙江人民出版社 · 后浪",
    year: "2017",
    tag: "书信集",
    cat: "随笔书信",
    desc: "现代文学批评界两大巨擘的六百余封私密书信，十七年间谈文论艺、殷勤存问的吉光片羽。从治学门径到文坛月旦，从异乡生计到手足深情，书信里的夏氏兄弟卸下学术盛名，露出最真切的性情与时代侧影。",
    cover: "covers/xiazhiqing.jpg",
    palette: { bg: "#ece6db", ink: "#31404f", accent: "#5b7a99", coverA: "#f4f0e8", coverB: "#c6cfd8", coverInk: "#31404f" }
  },
  {
    title: "漫谈中国文化",
    sub: "金融 · 企业 · 国学",
    author: "南怀瑾 讲述",
    origin: "中",
    translator: "",
    publisher: "东方出版社",
    year: "2008",
    tag: "国学讲录",
    cat: "哲学宗教",
    desc: "太湖大学堂三次讲座辑录：从《管子》《货殖列传》谈起，纵论传统文化中的金融、企业与经济之道。南怀瑾以一贯的博闻纵横、亦庄亦谐，把经史子集里的经济智慧讲入当下，为企业家与读书人开一剂清凉散。",
    cover: "covers/mantan.jpg",
    palette: { bg: "#f0e7d8", ink: "#54331d", accent: "#b8860b", coverA: "#e9d9ba", coverB: "#f7f0e2", coverInk: "#54331d" }
  },
  {
    title: "未厌居习作",
    sub: "",
    author: "叶绍钧（叶圣陶）",
    origin: "中",
    translator: "",
    publisher: "中国青年出版社",
    year: "1935 / 2012",
    tag: "现代散文",
    cat: "随笔书信",
    desc: "\u201c未厌居\u201d为叶圣陶书斋之名。文字淳厚平实，一位现代文学与教育大家对日常生活的静观。游记、忆旧、谈文、论教，篇篇如话家常，于平淡处见性情；读其文如见其人——诚恳克己，把白话散文写到了炉火纯青。",
    cover: "covers/weiyanju.jpg",
    palette: { bg: "#e4e7e3", ink: "#3c4a41", accent: "#748c7d", coverA: "#f2f4f1", coverB: "#cdd6cf", coverInk: "#3c4a41" }
  },
  {
    title: "金陵汉诗",
    sub: "",
    author: "邓攀 编著",
    origin: "中",
    translator: "",
    publisher: "南京出版社",
    year: "2019",
    tag: "诗歌 · 地方文史",
    cat: "诗歌",
    desc: "辑录与金陵相关的汉诗作品，在字句平仄间打捞一座古都绵延千年的诗意文脉。从六朝烟水到明清风月，秦淮、钟山、台城次第入诗，一册在手，可作金陵怀古的文学地图，也是南京城市记忆的别样档案。",
    palette: { bg: "#cfe8e6", ink: "#1f4e4a", accent: "#2e7d76", coverA: "#5cb8ae", coverB: "#e8f5f3", coverInk: "#134744" }
  },
  {
    title: "金刚经讲义",
    sub: "",
    author: "江味农",
    origin: "中",
    translator: "",
    publisher: "华东师范大学出版社 等",
    year: "1940年代成书",
    tag: "佛学",
    cat: "哲学宗教",
    desc: "民国居士江味农倾注毕生心血的遗著，被誉为解释《金刚经》的最佳读本之一。逐句科判、字字推敲，融唯识与般若于一炉，既是佛学研究的严谨范本，也为普通读者铺就一条读懂“应无所住而生其心”的门径。",
    cover: "covers/jingang.jpg",
    palette: { bg: "#efe3cf", ink: "#5a4326", accent: "#a67c3d", coverA: "#d9c193", coverB: "#f5ecda", coverInk: "#5a4326" }
  },
  {
    title: "蛮族世界的拼图",
    sub: "The Barbarians",
    author: "彼得·柏伽基",
    origin: "波",
    translator: "",
    publisher: "中国社会科学出版社 · 鼓楼新悦",
    year: "2021",
    tag: "考古 · 欧洲史",
    cat: "社科历史",
    desc: "在希腊罗马的文字记载之外，用考古证据重建欧洲史前居民数千年的真实生活图景。巨石阵的建造者、阿尔卑斯冰人、维京航海者——那些被称作“蛮族”的人群，其实有着远比史书记载更复杂精彩的文明。",
    cover: "covers/manzu.jpg",
    palette: { bg: "#4a4a42", ink: "#e9e5d8", accent: "#c2a25a", coverA: "#5c5a4c", coverB: "#3a3a34", coverInk: "#e9e5d8" }
  },
  {
    title: "霍布斯与共和主义自由",
    sub: "Hobbes and Republican Liberty",
    author: "昆廷·斯金纳",
    origin: "英",
    translator: "",
    publisher: "上海三联书店",
    year: "2011",
    tag: "政治哲学",
    cat: "哲学宗教",
    desc: "剑桥思想史学派代表作：围绕霍布斯与古典共和主义关于\u201c自由\u201d的论争，重构现代政治思想的关键脉络。斯金纳细读《利维坦》的修辞与语境，展示霍布斯如何一步步瓦解“自由邦”理想，也照亮我们今天谈论自由的方式。",
    cover: "covers/hobbes.jpg",
    palette: { bg: "#f4f1ea", ink: "#23211e", accent: "#8c8577", coverA: "#faf8f3", coverB: "#dcd6c9", coverInk: "#23211e" }
  },
  {
    title: "中国古建筑二十讲",
    sub: "",
    author: "楼庆西",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2001",
    tag: "建筑文化",
    cat: "艺术设计",
    desc: "清华建筑学者的经典讲义：以二十讲通俗系统地讲述中国古建筑的类型、结构与文化内涵。从紫禁城的中轴到江南园林的曲径，从斗拱榫卯到风水观念，图文并茂，是普通读者走近中国古建筑最平易的一扇门。",
    cover: "covers/gujianzhu.jpg",
    palette: { bg: "#3d2b26", ink: "#eadfd0", accent: "#c8552c", coverA: "#5a3a30", coverB: "#2e211d", coverInk: "#eadfd0" }
  },
  {
    title: "中国古代纪时考",
    sub: "",
    author: "张衍田",
    origin: "中",
    translator: "",
    publisher: "上海古籍出版社",
    year: "2019",
    tag: "文史考据",
    cat: "社科历史",
    desc: "对中国古代纪年、纪月、纪日、纪时制度的系统考证，文史研究者的案头工具书。干支如何配日、岁星如何纪年、十二时辰如何划分——读古书绕不开的时间问题，皆可在此一一检得源流与定说。",
    cover: "covers/jishikao.jpg",
    palette: { bg: "#4b2530", ink: "#ecdfd2", accent: "#caa14e", coverA: "#5f3040", coverB: "#3a1c26", coverInk: "#ecdfd2" }
  },
  {
    title: "人类简史",
    sub: "Sapiens: A Brief History of Humankind",
    author: "尤瓦尔·赫拉利",
    origin: "以",
    translator: "林俊宏",
    publisher: "中信出版社",
    year: "2014",
    tag: "历史 · 社科",
    cat: "社科历史",
    desc: "从认知革命、农业革命到科学革命，赫拉利以宏大视角重述十万年人类史，追问智人何以主宰地球、又将走向何方。虚构故事的力量、金钱与帝国的秩序、快乐的历史学——这部全球现象级畅销书，改变了无数人看待历史与自身的方式。",
    cover: "covers/renlei.jpg",
    palette: { bg: "#e8e6e1", ink: "#2b2b2b", accent: "#c89b5a", coverA: "#d9d5cd", coverB: "#f2f0ec", coverInk: "#2b2b2b" }
  },
  {
    title: "古希腊社会生活史",
    sub: "那些不在历史书里的事儿",
    author: "达玛丽斯·罗梅罗·冈萨雷斯",
    origin: "西",
    translator: "宋若筠",
    publisher: "金城出版社",
    year: "2026",
    tag: "古典 · 生活史",
    cat: "社科历史",
    desc: "告别冰冷的宏大叙事，走进古希腊人的烟火日常：从私人生活到大众文化，看见一个鲜活、怪诞而迷人的古希腊社会。他们如何恋爱、宴饮、看戏、掷骰子？那些不在历史书里的事儿，恰恰最能让两千年前的世界活起来。",
    cover: "covers/guxila.jpg",
    palette: { bg: "#17181c", ink: "#ece7db", accent: "#c9a227", coverA: "#23252c", coverB: "#101114", coverInk: "#ece7db" }
  },
  {
    title: "我的生活很重要",
    sub: "过自己想要的生活",
    author: "彭瑞心",
    origin: "中",
    translator: "",
    publisher: "中信出版集团",
    year: "2026",
    tag: "生活 · 随笔",
    cat: "随笔书信",
    desc: "家庭美学实践者“啾啾妈”首部作品：从忙乱到从容，把日子变轻松的36个解法。收纳动线、家务分工、亲子时间与自我照顾——不贩卖完美生活，只提供可上手的具体方法，把想要的生活落到每一个日常。",
    cover: "covers/wodeshenghuo.jpg",
    palette: { bg: "#8e3b3b", ink: "#f7ece4", accent: "#e0b089", coverA: "#96403f", coverB: "#7a3232", coverInk: "#f7ece4" }
  },
  {
    title: "当战争来敲门",
    sub: "二战中的经济、人性和平民",
    author: "理查德·奥弗里 主编",
    origin: "英",
    translator: "刘晓同 / 刘志良",
    publisher: "江苏凤凰文艺出版社",
    year: "2025",
    tag: "二战史",
    cat: "社科历史",
    desc: "牛津大学出版社原版引进：从经济崩溃到全面战争，谁是推手？谁上战场？谁在幕后？谁得利益？多位顶尖二战史学者合力，把镜头从统帅部转向工厂、田野与家庭，看总体战如何碾过每一个普通人的生活。",
    cover: "covers/dangzhanzheng.jpg",
    palette: { bg: "#1c2a4a", ink: "#e9ecf2", accent: "#d64545", coverA: "#24365e", coverB: "#16223c", coverInk: "#e9ecf2" }
  },
  {
    title: "治世与烟火",
    sub: "中国古代官僚制度与社会生活史",
    author: "郭建",
    origin: "中",
    translator: "",
    publisher: "团结出版社",
    year: "2025",
    tag: "制度史",
    cat: "社科历史",
    desc: "复旦大学教授以史学巨眼透视制度肌理，看两千年来“治世”理想与“烟火”现实的碰撞。从科举铨选到胥吏生态，从赋税徭役到市井营生，制度如何塑造日常、日常又如何消解制度，在庙堂与江湖之间读懂古代中国的运转逻辑。",
    cover: "covers/zhishi.jpg",
    palette: { bg: "#efe6d6", ink: "#4a3421", accent: "#b8442c", coverA: "#f4ecdd", coverB: "#ddcdb2", coverInk: "#4a3421" }
  },
  {
    title: "古人的日常生活（全五册）",
    sub: "服饰 · 膳食 · 茶饮 · 把玩 · 家居",
    author: "陈元綵 等",
    origin: "中",
    translator: "",
    publisher: "北京理工大学出版社",
    year: "2022",
    tag: "传统文化",
    cat: "社科历史",
    desc: "一套古人日常生活百科：从衣冠服饰到茶饮膳食、家居陈设与赏玩之物，图文重建古代中国人的衣食住行。深衣如何裁、点茶如何斗、香篆如何燃、案头清供如何摆，五册分类细讲，是传统生活美学的入门图谱。",
    cover: "covers/gurenrichang.jpg",
    palette: { bg: "#ece2cf", ink: "#5a4632", accent: "#c0392b", coverA: "#f2e9d8", coverB: "#d9c9ac", coverInk: "#5a4632" }
  },
  {
    title: "全球化突围",
    sub: "模式、架构与风险防控",
    author: "鲍乐东",
    origin: "中",
    translator: "",
    publisher: "浙江大学出版社",
    year: "2026",
    tag: "商业 · 管理",
    cat: "商业经管",
    desc: "模式选择×架构设计×风险防控，企业出海全链路实战体系，直击中国企业全球化的隐形陷阱。从市场准入、合规架构到跨文化管理，作者以大量一线案例拆解出海各环节的关键决策，为不同体量的企业给出可落地的全球化路线图。",
    cover: "covers/quanqiuhua.jpg",
    palette: { bg: "#1d4f9e", ink: "#f0f4fa", accent: "#7fb2f0", coverA: "#2458aa", coverB: "#163e80", coverInk: "#f0f4fa" }
  },
  {
    title: "即兴表达",
    sub: "轻松留下好印象的沟通技巧",
    author: "王达峰",
    origin: "中",
    translator: "",
    publisher: "浙江大学出版社",
    year: "2020",
    tag: "沟通 · 成长",
    cat: "商业经管",
    desc: "15秒抓住注意力，3句话说清楚重点——从逻辑到共情，用模型与结构掌控每一个沟通的关键时刻。电梯汇报、临场发言、会议插话、饭局祝辞，书中把高频场景一一拆解成可练习的表达框架，让不善言辞的人也能即兴开口、言之有物。",
    cover: "covers/jixing.jpg",
    palette: { bg: "#f3d9c9", ink: "#3f3a36", accent: "#8aa87c", coverA: "#f7e3d6", coverB: "#e8c8b4", coverInk: "#3f3a36" }
  },
  {
    title: "27小时事件经济",
    sub: "",
    author: "张毅成",
    origin: "中",
    translator: "",
    publisher: "东方出版社",
    year: "2025",
    tag: "营销 · 传播",
    cat: "商业经管",
    desc: "不到27小时，只是热闹；超过27小时，才是经济——解码事件营销的传播周期与商业转化。作者复盘众多现象级传播案例，提出事件从引爆、发酵到变现的时间窗口理论，为品牌方提供把流量转化为增长的操作方法。",
    cover: "covers/ershiqi.jpg",
    palette: { bg: "#21294a", ink: "#f0eeea", accent: "#d8322e", coverA: "#d8322e", coverB: "#21294a", coverInk: "#ffffff" }
  },
  {
    title: "商人与中国社会",
    sub: "一部共生演进史",
    author: "陈润 / 邓玉蕊",
    origin: "中",
    translator: "",
    publisher: "浙江大学出版社",
    year: "2026",
    tag: "商业史",
    cat: "商业经管",
    desc: "商人以实业推动社会进步，社会以制度为商人划定发展方向——书写中国商业与社会的千年演进篇章。从范蠡、胡雪岩到近代实业家，从盐铁专营到民营经济，在商人群体的沉浮里，读出中国社会结构与商业文明的共生密码。",
    cover: "covers/shangren.jpg",
    palette: { bg: "#101d33", ink: "#e8e2d2", accent: "#caa969", coverA: "#16263f", coverB: "#0b1523", coverInk: "#e8e2d2" }
  },
  {
    title: "财报决策力",
    sub: "从关键数据分析到高效决策",
    author: "徐晶",
    origin: "中",
    translator: "",
    publisher: "中国友谊出版公司",
    year: "2026",
    tag: "财务 · 管理",
    cat: "商业经管",
    desc: "企业主、管理层、债权人、投资人的实战手册：穿透关键数据背后的盈利能力、营运能力与投资价值。三张报表如何联动、哪些指标暗藏风险、如何用财务视角做经营决策，作者以真实企业案例带你把财报读成决策工具。",
    cover: "covers/juece.jpg",
    palette: { bg: "#b02722", ink: "#fdf3ea", accent: "#d9a45c", coverA: "#ba2d26", coverB: "#8f1e1a", coverInk: "#fdf3ea" }
  },
  {
    title: "帝国棋局",
    sub: "张居正的晚明改革与博弈",
    author: "齐悦",
    origin: "中",
    translator: "",
    publisher: "中国友谊出版公司",
    year: "2026",
    tag: "明史",
    cat: "社科历史",
    desc: "孤臣铁腕，挽倾颓之国——十年改革，续大明天命。在权谋与困局交织处，重看张居正的人生史诗。考成法如何整肃官僚、一条鞭法如何再造财政，而人亡政息的结局，又给这场晚明最后的自救留下怎样的历史回响。",
    cover: "covers/diguoqiju.jpg",
    palette: { bg: "#f4e3c8", ink: "#7a3a1c", accent: "#b4552a", coverA: "#f8ecd6", coverB: "#e6c9a0", coverInk: "#7a3a1c" }
  },
  {
    title: "精神帝国",
    sub: "Empires of the Mind",
    author: "罗伯特·吉尔德",
    origin: "英",
    translator: "孙伟",
    publisher: "浙江大学出版社",
    year: "2026",
    tag: "帝国史",
    cat: "社科历史",
    desc: "殖民历史与当代政治：追溯冷战结束以来帝国主义思维的复苏，剖析英法帝国遗产如何塑造当下。从苏伊士运河到脱欧公投，从法属非洲到移民政策，作者揭示帝国记忆如何持续左右两个老牌殖民国家的自我想象与世界角色。",
    cover: "covers/jingshendiguo.jpg",
    palette: { bg: "#e9e4d4", ink: "#24211c", accent: "#d8b93c", coverA: "#efece1", coverB: "#d8cdb2", coverInk: "#24211c" }
  },
  {
    title: "太平前夜",
    sub: "五代十国的乱世诗心",
    author: "陈尚君",
    origin: "中",
    translator: "",
    publisher: "上海人民出版社",
    year: "2026",
    tag: "文学史",
    cat: "社科历史",
    desc: "唐诗学大家陈尚君新作：在五代十国的兵戈乱世里，打捞诗人们未曾燄灭的诗心与斯文。韦庄、罗隐、冯道……乱世文人如何在朝不保夕中安顿文字与性命，五十年离乱亦是宋代文治的前夜，斯文不坠自有其人。",
    cover: "covers/taiping.jpg",
    palette: { bg: "#2b2d7e", ink: "#ece4d2", accent: "#d9a441", coverA: "#34378f", coverB: "#1f2160", coverInk: "#ece4d2" }
  },
  {
    title: "红顶商人胡雪岩",
    sub: "",
    author: "高阳",
    origin: "台",
    translator: "",
    publisher: "江苏文艺出版社 · 读客",
    year: "2012",
    tag: "历史小说",
    cat: "文学小说",
    desc: "讲透中国传统商道人情的至高经典：从店伙计到大清首富只用了30年，从首富到抄家破产只用了3天。高阳以细腻的世情笔法写尽官商之道、人情练达与时代宿命，被无数企业家奉为理解中国式经商智慧的案头书。",
    cover: "covers/hongding.jpg",
    palette: { bg: "#1a1714", ink: "#efe6d8", accent: "#cf2f24", coverA: "#262019", coverB: "#0f0d0b", coverInk: "#efe6d8" }
  },
  {
    title: "未央歌",
    sub: "",
    author: "鹿桥",
    origin: "中",
    translator: "",
    publisher: "黄山书社",
    year: "2007",
    tag: "长篇小说",
    cat: "文学小说",
    desc: "以西南联大为背景的青春长歌：战火中的昆明校园，一群大学生的友情、爱情与理想主义岁月。小童、伍宝笙、余孟勤、蔺燕梅，四个名字承载了几代读者的青春记忆——纵然烽火连天，歌声未央，人间仍值得深情以待。",
    cover: "covers/weiyangge.jpg",
    palette: { bg: "#33504e", ink: "#dfe6e2", accent: "#86a89f", coverA: "#3c5c58", coverB: "#253c3a", coverInk: "#dfe6e2" }
  },
  {
    title: "大唐李白·凤凰台",
    sub: "",
    author: "张大春",
    origin: "台",
    translator: "",
    publisher: "广西师范大学出版社 · 理想国",
    year: "2014",
    tag: "历史小说",
    cat: "文学小说",
    desc: "融历史、传记、小说、诗论于一体：重建灿烂迷离的盛唐景观，再现李白声名背后的斑斓世相。此卷写李白出蜀之后的游历与干谒，在金陵凤凰台的登临怀古间，张大春以考据入小说，逐句拆解诗仙如何炼字成名。",
    cover: "covers/datangli.jpg",
    palette: { bg: "#f2ece2", ink: "#322c28", accent: "#b7383e", coverA: "#b7383e", coverB: "#f6f1e7", coverInk: "#ffffff" }
  },
  {
    title: "大唐李白·将进酒",
    sub: "",
    author: "张大春",
    origin: "台",
    translator: "",
    publisher: "广西师范大学出版社 · 理想国",
    year: "2015",
    tag: "历史小说",
    cat: "文学小说",
    desc: "“大唐李白”第三卷：古来圣贤皆寂寞，惟有饮者留其名——李白浪游长安前夜的诗与远方。娶妻安陆、蹉跎干谒、诗酒放浪，张大春继续以小说笔法与诗学考证双线并进，写出盛唐光环之下一个诗人真实的困顿与狂傲。",
    cover: "covers/jiangjinjiu.jpg",
    palette: { bg: "#ececea", ink: "#33302c", accent: "#8f8a82", coverA: "#f4f3f0", coverB: "#d8d6d1", coverInk: "#33302c" }
  },
  {
    title: "北归记·接引葫芦",
    sub: "《野葫芦引》第四卷 · 末卷",
    author: "宗璞",
    origin: "中",
    translator: "",
    publisher: "人民文学出版社",
    year: "2019",
    tag: "长篇小说",
    cat: "文学小说",
    desc: "“野葫芦引”四部曲收官之作：西南联大师生北归之后的命运流转，一代知识分子的心灵史诗。孟樾一家与明仑大学同仁重返北平，在时代巨变的前夜各自抉择，宗璞以九旬高龄完成这部写了三十余年的长篇绝唱。",
    cover: "covers/beiguiji.jpg",
    palette: { bg: "#f0f2f4", ink: "#3a4a6b", accent: "#5b74a8", coverA: "#f7f8fa", coverB: "#dfe4ec", coverInk: "#3a4a6b" }
  },
  {
    title: "我们并不知道",
    sub: "",
    author: "金宇澄",
    origin: "中",
    translator: "",
    publisher: "东美出版（台北）",
    year: "2017",
    tag: "随笔 · 谈话",
    cat: "随笔书信",
    desc: "《繁花》作者金宇澄的随笔谈话集：关于记忆、城市与写作，那些“我们并不知道”的人间细节。上海弄堂的旧物、东北农场的岁月、小说家的手艺与耳闻——金宇澄以不响的姿态娓娓道来，处处是《繁花》之外的底稿与余味。",
    cover: "covers/bingbuzhidao.jpg",
    palette: { bg: "#cbb287", ink: "#3c2f1c", accent: "#8c6b3a", coverA: "#d8c49b", coverB: "#b89a68", coverInk: "#3c2f1c" }
  },
  {
    title: "千江有水千江月",
    sub: "",
    author: "萧丽红",
    origin: "台",
    translator: "",
    publisher: "人民文学出版社",
    year: "2006",
    tag: "长篇小说",
    cat: "文学小说",
    desc: "台湾文学经典：布袋镇的大家族里，贞观与大信含蓄悠长的爱情，写尽旧式人情之美。节庆、渔汛、婚丧、书信，萧丽红以温润的闽南风土为底色，让一段无疾而终的初恋，成为中文世界最动人的古典深情。",
    cover: "covers/qianjiang.jpg",
    palette: { bg: "#f2f4f6", ink: "#2c4a72", accent: "#4a72a8", coverA: "#f8fafc", coverB: "#dbe6f0", coverInk: "#2c4a72" }
  },
  {
    title: "书店四季",
    sub: "Confessions of a Bookseller",
    author: "肖恩·白塞尔",
    origin: "英",
    translator: "顾真",
    publisher: "北京日报出版社",
    year: "2021",
    tag: "书店 · 随笔",
    cat: "随笔书信",
    desc: "《书店日记》续篇：苏格兰最大二手书店又一年——毒舌店主与顾客、店猫和旧书相伴的四季流水账。收书、估价、应付奇葩客人与亚马逊的挤压，白塞尔以英式冷幽默记录实体书店的困顿与可爱，献给所有仍愿走进书店的人。",
    cover: "covers/shudianriji.jpg",
    palette: { bg: "#1f6f5c", ink: "#f4efdd", accent: "#e0475c", coverA: "#268069", coverB: "#164f42", coverInk: "#f4efdd" }
  },
  {
    title: "诗里的大唐",
    sub: "由诗人的命运与诗作交织成的大唐史",
    author: "最爱君",
    origin: "中",
    translator: "",
    publisher: "时报文化",
    year: "2022",
    tag: "诗歌 · 唐史",
    cat: "诗歌",
    desc: "诗以言史，史以入诗：在李白杜甫们的悲欢浮沉里，读懂大唐三百年的兴衰流转。以诗人命运为经、以诗作为纬，从初唐四杰到晚唐李商隐，一部由诗串起的大唐编年史，让课本里的名句回到它们诞生的历史现场。",
    palette: { bg: "#efe1c6", ink: "#6b3a20", accent: "#c2452c", coverA: "#e8d3a8", coverB: "#f6ecd8", coverInk: "#6b3a20" }
  },
  {
    title: "难以驯化的利维坦",
    sub: "基于韦伯“国家社会学”的研究",
    author: "陈涛",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2026",
    tag: "政治社会学",
    cat: "社科历史",
    desc: "三联·哈佛燕京学术丛书：以韦伯“国家社会学”为鑰，剖析现代国家这头难以驯化的利维坦。官僚制、正当性与暴力垄断如何相互缠绕，国家理性又如何在民主时代持续膨胀，作者在韦伯文本的细读中回应当代政治的根本追问。",
    cover: "covers/liweitan.jpg",
    palette: { bg: "#dfe5df", ink: "#2c433a", accent: "#52705f", coverA: "#b9c8bd", coverB: "#33544a", coverInk: "#eef2ee" }
  },
  {
    title: "万历十五年",
    sub: "1587, a Year of No Significance",
    author: "黄仁宇",
    origin: "美",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "1997",
    tag: "明史经典",
    cat: "社科历史",
    desc: "大历史观开山之作：万历十五年，表面四海升平，实则大明王朝的症结已在无声处一一显露。万历皇帝、张居正、海瑞、戚继光、李贽——六个人物的困局拼出一个以道德代替法制的体制之殇，影响了几代中国读者的历史观。",
    cover: "covers/wanli.jpg",
    palette: { bg: "#efe9db", ink: "#4a3d2a", accent: "#a08050", coverA: "#f4efe2", coverB: "#d9cdb2", coverInk: "#4a3d2a" }
  },
  {
    title: "伽达默尔与东方思想",
    sub: "与伽达默尔同行",
    author: "张能为",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2026",
    tag: "哲学",
    cat: "哲学宗教",
    desc: "“与伽达默尔同行”书系：考察诠释学大师与东方思想的对话可能，探寻中西哲学互鉴的路径。从“视域融合”到儒道经典的现代解读，作者梳理伽达默尔晚年对东方的关切，为跨文化诠释学开出一条中国进路。",
    cover: "covers/gadamoer.jpg",
    palette: { bg: "#16457e", ink: "#eef2f7", accent: "#d4763a", coverA: "#1c528f", coverB: "#0f3560", coverInk: "#eef2f7" }
  },
  {
    title: "新定位时代",
    sub: "定位决定地位，眼界决定境界",
    author: "邓德隆",
    origin: "中",
    translator: "",
    publisher: "上海三联书店",
    year: "2022",
    tag: "商业 · 战略",
    cat: "商业经管",
    desc: "特劳特全球总裁邓德隆二十年定位实践：郎酒、方太、加多宝等分行业案例的战略心法。在流量红利消退的新竞争环境下，如何重新占据心智、界定竞争对手、配置企业资源，一部写给中国企业家的定位理论落地手册。",
    cover: "covers/xindingwei.jpg",
    palette: { bg: "#14523c", ink: "#f0ead8", accent: "#d43a2a", coverA: "#185f46", coverB: "#0d3d2c", coverInk: "#f0ead8" }
  },
  {
    title: "星汉灿烂，幸甚至哉",
    sub: "",
    author: "关心则乱",
    origin: "中",
    translator: "",
    publisher: "江苏凤凰文艺出版社",
    year: "2022",
    tag: "古代言情",
    cat: "文学小说",
    desc: "一个女孩子的成长：程少商与凌不疑的东汉风云，热播剧《星汉灿烂》原著小说。缺爱的将门孤女以小聪明在深宅与朝堂间求生，与身世成谜的皇帝养子相遇相知——是甜宠言情，也是一部关于自愈与成长的女性叙事。",
    cover: "covers/jianan.jpg",
    palette: { bg: "#1c2b4a", ink: "#f2e6d8", accent: "#e08a4a", coverA: "#253a63", coverB: "#131f38", coverInk: "#f2e6d8" }
  },
  {
    title: "正义的褶皱",
    sub: "热点案件的法理重构",
    author: "桑本谦",
    origin: "中",
    translator: "",
    publisher: "生活·读书·新知三联书店",
    year: "2026",
    tag: "法学",
    cat: "社科历史",
    desc: "深度拆解十大热点案例：不止还原案件来龙去脉，更聚焦法律的底层逻辑，培养法律直觉。于欢案、电梯劝烟案、货拉拉案……桑本谦以法经济学的锋利刀法剖开舆论漩涡中的疑难案件，展示法理如何在情与法的褶皱处展开。",
    cover: "covers/zhengyi.jpg",
    palette: { bg: "#232c40", ink: "#edeef2", accent: "#b03030", coverA: "#2c3852", coverB: "#171d2c", coverInk: "#edeef2" }
  },
  {
    title: "记忆",
    sub: "Anamnesis · 历史与政治理论",
    author: "埃里克·沃格林",
    origin: "美",
    translator: "朱成明",
    publisher: "华东师范大学出版社",
    year: "2017",
    tag: "政治哲学",
    cat: "哲学宗教",
    desc: "沃格林思想成熟期的核心文本：以“记忆”为轴，追索历史与政治理论中意识哲学的根基。从对胡塞尔的批判到“天下时代”的酝酿，本书记录了沃格林哲学的关键转折，是进入其庞大秩序哲学体系的必经门户。",
    cover: "covers/huiyi.jpg",
    palette: { bg: "#e6ddd0", ink: "#40332a", accent: "#8c4a32", coverA: "#efe8dc", coverB: "#d4c7b4", coverInk: "#40332a" }
  }
];
